### ISSUE TITLE
[Bug] emit main function that returns `int`

### ISSUE THREAD

**Issue by ksolana** [solana-labs/move#93] opened 2023-04-20 04:55 UTC
rbpf expects a function that returns a status code, but we
currently emit a main function that returns void, so this value
is seemingly whatever happens to be in the return register.

Also see: language/tools/move-mv-llvm-compiler/tests/rbpf-tests.rs

**Comment by nvjle** [comment] 2023-04-24 01:15
This is a duplicate of https://github.com/solana-labs/move/issues/81.

**Closed** 2023-04-24 01:16 UTC
Labels: bug
